AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rbf2ics

  https://github.com/leitosama/rbf2ics

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  RBF2ICSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: rbf2ics/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Events:
        RBF2ICS:
          Type: Api # Use API as Event Source!
          Properties:
            Path: /rbf2ics
            Method: get